color:
-   - "RAL 1003 Signalgelb"
    - [4964, 3532, 2667]
-   - "RAL C=30 M=10 Y=30 K=0 grünbläulich"
    - [5107, 4897, 4247]
-   - "RAL 3013 Tomatenrot"
    - [3614, 2515, 2300]
-   - "RAL C=30 M=0 Y=80 K=0 grünlich"
    - [5064, 4639, 3282]
-   - "RAL 8001 Ockerbraun"
    - [3107, 2605, 2261]
-   - "RAL 7016 Anthrazitgrau"
    - [2548, 2377, 2150]
-   - "RAL 2009 Verkehrsorange"
    - [4691, 2710, 2418]
-   - "RAL 5010 Enzianblau"
    - [2643, 2665, 2751]
-   - "RAL 4004 Bordeauxviolett"
    - [2894, 2388, 2212]
-   - "RAL 6034 Pastelltürkis"
    - [3710, 3917, 3613]
-   - "RAL C=10 M=20 Y=20 K=0 zartrosa"
    - [5733, 4963, 4393]
-   - "RAL weiss"
    - [5886, 5369, 4787]
desc: "Configuration file für erste Kalibrierung mit echten Museumswürfeln"
det: {threshold: 10}
# max_dist: max distance between rgb colors.
rgb: {stable_cnt: 10, stable_dist: 7, max_dist: 800}
sensor:
    gain: !!python/tuple [2]
    integration_time: !!python/tuple [235]
map_station_mp3_color:
    - [1, 011_Ti1_Rollenspiel_Albrecht-Duerer.mp3, "RAL 1003 Signalgelb"]
    - [1, 011e_Ti1_Roleplay_Albrecht-Duerer.mp3, "RAL 2009 Verkehrsorange"]
    - [1, 012_Ti1_Rollenspiel_Lara-Croft.mp3, "RAL C=30 M=10 Y=30 K=0 grünbläulich"]
    - [1, 012e_Ti1_Roleplay_Lara-Croft.mp3, "RAL 5010 Enzianblau"]
    - [1, 013_Ti1_Rollenspiel_Manga.mp3, "RAL 3013 Tomatenrot"]
    - [1, 013e_Ti1_Roleplay_Manga.mp3, "RAL 4004 Bordeauxviolett"]
    - [1, 014_Ti1_Rollenspiel_Nbg-Docke.mp3, "RAL C=30 M=0 Y=80 K=0 grünlich"]
    - [1, 014e_Ti1_Roleplay_Nbg-Docke.mp3, "RAL 6034 Pastelltürkis"]
    - [1, 015_Ti1_Rollenspiel_Roboter.mp3, "RAL 8001 Ockerbraun"]
    - [1, 015e_Ti1_Roleplay_Roboter.mp3, "RAL C=10 M=20 Y=20 K=0 zartrosa"]
    - [2, 021_Ti2_bauen-konstruieren_Albrecht-Duerer.mp3, "RAL 1003 Signalgelb"]
    - [2, 021e_Ti2_construction_Albrecht-Duerer.mp3, "RAL 2009 Verkehrsorange"]
    - [2, 022_Ti2_bauen-konstruieren_Lara-Croft.mp3, "RAL C=30 M=10 Y=30 K=0 grünbläulich"]
    - [2, 022e_Ti2_construction_Lara-Croft.mp3, "RAL 5010 Enzianblau"]
    - [2, 023_Ti2_bauen-konstruieren_Manga.mp3, "RAL 3013 Tomatenrot"]
    - [2, 023e_Ti2_construction_Manga.mp3, "RAL 4004 Bordeauxviolett"]
    - [2, 024_Ti2_bauen-konstruieren_Nbg-Docke.mp3, "RAL C=30 M=0 Y=80 K=0 grünlich"]
    - [2, 024e_Ti2_construction_Nbg-Docke.mp3, "RAL 6034 Pastelltürkis"]
    - [2, 025_Ti2_bauen-konstruieren_Roboter.mp3, "RAL 8001 Ockerbraun"]
    - [2, 025e_Ti2_construction_Roboter.mp3, "RAL C=10 M=20 Y=20 K=0 zartrosa"]
    - [3, 031_Ti3_Geschicklichkeit_Albrecht-Duerer.mp3, "RAL 1003 Signalgelb"]
    - [3, 031e_Ti3_skill_Albrecht-Duerer.mp3, "RAL 2009 Verkehrsorange"]
    - [3, 032_Ti3_Geschicklichkeit_Lara-Croft.mp3, "RAL C=30 M=10 Y=30 K=0 grünbläulich"]
    - [3, 032e_Ti3_skill_Lara-Croft.mp3, "RAL 5010 Enzianblau"]
    - [3, 033_Ti3_Geschicklichkeit_Manga.mp3, "RAL 3013 Tomatenrot"]
    - [3, 033e_Ti3_skill_Manga.mp3, "RAL 4004 Bordeauxviolett"]
    - [3, 034_Ti3_Geschicklichkeit_Nbg-Docke.mp3, "RAL C=30 M=0 Y=80 K=0 grünlich"]
    - [3, 034e_Ti3_skill_Nbg-Docke.mp3, "RAL 6034 Pastelltürkis"]
    - [3, 035_Ti3_Geschicklichkeit_Roboter.mp3, "RAL 8001 Ockerbraun"]
    - [3, 035e_Ti3_skill_Roboter.mp3, "RAL C=10 M=20 Y=20 K=0 zartrosa"]
    - [4, 041_Ti4_Beziehung_Albrecht-Duerer.mp3, "RAL 1003 Signalgelb"]
    - [4, 041e_Ti4_relationship_Albrecht-Duerer.mp3, "RAL 2009 Verkehrsorange"]
    - [4, 042_Ti4_Beziehung_Lara-Croft.mp3, "RAL C=30 M=10 Y=30 K=0 grünbläulich"]
    - [4, 042e_Ti4_relationship_Lara-Croft.mp3, "RAL 5010 Enzianblau"]
    - [4, 043_Ti4_Beziehung_Manga.mp3, "RAL 3013 Tomatenrot"]
    - [4, 043e_Ti4_relationship_Manga.mp3, "RAL 4004 Bordeauxviolett"]
    - [4, 044_Ti4_Beziehung_Nbg-Docke.mp3, "RAL C=30 M=0 Y=80 K=0 grünlich"]
    - [4, 044e_Ti4_relationship_Nbg-Docke.mp3, "RAL 6034 Pastelltürkis"]
    - [4, 045_Ti4_Beziehung_Roboter.mp3, "RAL 8001 Ockerbraun"]
    - [4, 045e_Ti4_relationship_Roboter.mp3, "RAL C=10 M=20 Y=20 K=0 zartrosa"]
    - [5, 051_Ti5_Begreifen_Albrecht-Duerer.mp3, "RAL 1003 Signalgelb"]
    - [5, 051e_Ti5_toknow_Albrecht-Duerer.mp3, "RAL 2009 Verkehrsorange"]
    - [5, 052_Ti5_Begreifen_Lara-Croft.mp3, "RAL C=30 M=10 Y=30 K=0 grünbläulich"]
    - [5, 052e_Ti5_toknow_Lara-Croft.mp3, "RAL 5010 Enzianblau"]
    - [5, 053_Ti5_Begreifen_Manga.mp3, "RAL 3013 Tomatenrot"]
    - [5, 053e_Ti5_toknow_Manga.mp3, "RAL 4004 Bordeauxviolett"]
    - [5, 054_Ti5_Begreifen_Nbg-Docke.mp3, "RAL C=30 M=0 Y=80 K=0 grünlich"]
    - [5, 054e_Ti5_toknow_Nbg-Docke.mp3, "RAL 6034 Pastelltürkis"]
    - [5, 055_Ti5_Begreifen_Roboter.mp3, "RAL 8001 Ockerbraun"]
    - [5, 055e_Ti5_toknow_Roboter.mp3, "RAL C=10 M=20 Y=20 K=0 zartrosa"]
    - [6, 061_Ti6_Strategie_Albrecht-Duerer.mp3, "RAL 1003 Signalgelb"]
    - [6, 061e_Ti6_strategy_Albrecht-Duerer.mp3, "RAL 2009 Verkehrsorange"]
    - [6, 062_Ti6_Strategie_Lara-Croft.mp3, "RAL C=30 M=10 Y=30 K=0 grünbläulich"]
    - [6, 062e_Ti6_strategy_Lara-Croft.mp3, "RAL 5010 Enzianblau"]
    - [6, 063_Ti6_Strategie_Manga.mp3, "RAL 3013 Tomatenrot"]
    - [6, 063e_Ti6_strategy_Manga.mp3, "RAL 4004 Bordeauxviolett"]
    - [6, 064_Ti6_Strategie_Nbg-Docke.mp3, "RAL C=30 M=0 Y=80 K=0 grünlich"]
    - [6, 064e_Ti6_strategy_Nbg-Docke.mp3, "RAL 6034 Pastelltürkis"]
    - [6, 065_Ti6_Strategie_Roboter.mp3, "RAL 8001 Ockerbraun"]
    - [6, 065e_Ti6_strategy_Roboter.mp3, "RAL C=10 M=20 Y=20 K=0 zartrosa"]
    - [7, 071_Ti7_Technik_Albrecht-Duerer.mp3, "RAL 1003 Signalgelb"]
    - [7, 071e_Ti7_technics_Albrecht-Duerer.mp3, "RAL 2009 Verkehrsorange"]
    - [7, 072_Ti7_Technik_Lara-Croft.mp3, "RAL C=30 M=10 Y=30 K=0 grünbläulich"]
    - [7, 072e_Ti7_technics_Lara-Croft.mp3, "RAL 5010 Enzianblau"]
    - [7, 073_Ti7_Technik_Manga.mp3, "RAL 3013 Tomatenrot"]
    - [7, 073e_Ti7_technics_Manga.mp3, "RAL 4004 Bordeauxviolett"]
    - [7, 074_Ti7_Technik_Nbg-Docke.mp3, "RAL C=30 M=0 Y=80 K=0 grünlich"]
    - [7, 074e_Ti7_technics_Nbg-Docke.mp3, "RAL 6034 Pastelltürkis"]
    - [7, 075_Ti7_Technik_Roboter.mp3, "RAL 8001 Ockerbraun"]
    - [7, 075e_Ti7_technics_Roboter.mp3, "RAL C=10 M=20 Y=20 K=0 zartrosa"]
    - [8, 081_Ti8_Wirtschaften_Albrecht-Duerer.mp3, "RAL 1003 Signalgelb"]
    - [8, 081e_Ti8_economics_Albrecht-Duerer.mp3, "RAL 2009 Verkehrsorange"]
    - [8, 082_Ti8_Wirtschaften_Lara-Croft.mp3, "RAL C=30 M=10 Y=30 K=0 grünbläulich"]
    - [8, 082e_Ti8_economics_Lara-Croft.mp3, "RAL 5010 Enzianblau"]
    - [8, 083_Ti8_Wirtschaften_Manga.mp3, "RAL 3013 Tomatenrot"]
    - [8, 083e_Ti8_economics_Manga.mp3, "RAL 4004 Bordeauxviolett"]
    - [8, 084_Ti8_Wirtschaften_Nbg-Docke.mp3, "RAL C=30 M=0 Y=80 K=0 grünlich"]
    - [8, 084e_Ti8_economics_Nbg-Docke.mp3, "RAL 6034 Pastelltürkis"]
    - [8, 085_Ti8_Wirtschaften_Roboter.mp3, "RAL 8001 Ockerbraun"]
    - [8, 085e_Ti8_economics_Roboter.mp3, "RAL C=10 M=20 Y=20 K=0 zartrosa"]

