color:
-   - "RAL 1003 gelb"
    - [2906.0, 5897.0, 6807.0]
-   - "RAL 1001 beige"
    - [9253.0, 5998.5, 4077.0]
-   - "RAL 5024 pastelblau"
    - [10827.5, 10189.0, 5282.5]
-   - "RAL 5019 capriblau"
    - [8741.0, 5913.0, 4087.0]
-   - "RAL 3022 lachsrot"
    - [6037.0, 5466.0, 4849.0]
-   - "RAL 3013 tomatenrot"
    - [4623.0, 2855.0, 2770.0]
-   - "RAL 5018 türkisblau"
    - [22222, 22222, 22222]
-   - "RAL 6034 pasteltürkis"
    - [22222, 22222, 22222]
-   - "RAL 1000 grünbeige"
    - [22222, 22222, 22222]
-   - "RAL 6021 blassgrün"
    - [22222, 22222, 22222]
desc: "Configuration file für ersten Testaufbau mit Würfelhalter und schwarzen Schirmwürfel mittel"
det: {threshold: 5}
rgb: {stable_cnt: 10, stable_dist: 7, max_dist: 2000}
sensor:
    gain: !!python/tuple [1]
    integration_time: !!python/tuple [235]

