color:
-   - "Würfel blau"
    - [2049.0, 2014.0, 1854.0]
-   - "Würfel gelb"
    - [2591.0, 2229.0, 1758.0]
-   - "Würfel orange"
    - [2381.0, 1927.0, 1625.0]
-   - "Würfel weiss"
    - [2696.0, 2422.0, 2126.0]
-   - "Würfel rot"
    - [2371.0, 1870.0, 1687.0]
desc: "Configuration file für ersten Testaufbau mit Würfelhalter und schwarzen Schirmwürfel klein"
det: {threshold: 10}
rgb: {stable_cnt: 5, stable_dist: 10}
sensor:
    gain: !!python/tuple [2]
    integration_time: !!python/tuple [235]
