color:
-   - "RAL 5019 capriblau"
    - [3039.0, 3570.0, 3650.0]
-   - "RAL 5024 pastelblau"
    - [3049.0, 3580.0, 3656.0]
-   - "RAL 1003 gelb"
    - [5877.0, 4771.0, 3147.0]
-   - "RAL 1001 beige"
    - [5129.0, 3434.0, 2719.0]
-   - "RAL 3013 tomatenrot"
    - [6037.0, 5466.0, 4849.0]
-   - "RAL 3022 lachsrot"
    - [4623.0, 2855.0, 2770.0]
desc: "Configuration file für ersten Testaufbau mit Würfelhalter und schwarzen Schirmwürfel mittel"
det: {threshold: 5}
# max_dist: max distance between rgb colors.
rgb: {stable_cnt: 10, stable_dist: 7, max_dist: 800}
sensor:
    gain: !!python/tuple [2]
    integration_time: !!python/tuple [235]
map_station_mp3_color:
    - [1, 011_Ti1_Rollenspiel_Albrecht-Duerer.mp3, "RAL 1003 gelb"]
    - [1, 011e_Ti1_Roleplay_Albrecht-Duerer.mp3, "RAL 1001 beige"]
    - [1, 012_Ti1_Rollenspiel_Lara-Croft.mp3, "RAL 5024 pastelblau"]
    - [1, 012e_Ti1_Roleplay_Lara-Croft.mp3, "RAL 5019 capriblau"]
    - [1, 013_Ti1_Rollenspiel_Manga.mp3, "RAL 3022 lachsrot"]
    - [1, 013e_Ti1_Roleplay_Manga.mp3, "RAL 3013 tomatenrot"]
    - [1, 014_Ti1_Rollenspiel_Nbg-Docke.mp3, "RAL 5018 türkisblau"]
    - [1, 014e_Ti1_Roleplay_Nbg-Docke.mp3, "RAL 6034 pasteltürkis"]
    - [1, 015_Ti1_Rollenspiel_Roboter.mp3, "RAL 1000 grünbeige"]
    - [1, 015e_Ti1_Roleplay_Roboter.mp3, "RAL 6021 blassgrün"]
    - [2, 021_Ti2_bauen-konstruieren_Albrecht-Duerer.mp3, "RAL 1003 gelb"]
    - [2, 021e_Ti2_construction_Albrecht-Duerer.mp3, "RAL 1001 beige"]
    - [2, 022_Ti2_bauen-konstruieren_Lara-Croft.mp3, "RAL 5024 pastelblau"]
    - [2, 022e_Ti2_construction_Lara-Croft.mp3, "RAL 5019 capriblau"]
    - [2, 023_Ti2_bauen-konstruieren_Manga.mp3, "RAL 3022 lachsrot"]
    - [2, 023e_Ti2_construction_Manga.mp3, "RAL 3013 tomatenrot"]
    - [2, 024_Ti2_bauen-konstruieren_Nbg-Docke.mp3, "RAL 5018 türkisblau"]
    - [2, 024e_Ti2_construction_Nbg-Docke.mp3, "RAL 6034 pasteltürkis"]
    - [2, 025_Ti2_bauen-konstruieren_Roboter.mp3, "RAL 1000 grünbeige"]
    - [2, 025e_Ti2_construction_Roboter.mp3, "RAL 6021 blassgrün"]
    - [3, 031_Ti3_Geschicklichkeit_Albrecht-Duerer.mp3, "RAL 1003 gelb"]
    - [3, 031e_Ti3_skill_Albrecht-Duerer.mp3, "RAL 1001 beige"]
    - [3, 032_Ti3_Geschicklichkeit_Lara-Croft.mp3, "RAL 5024 pastelblau"]
    - [3, 032e_Ti3_skill_Lara-Croft.mp3, "RAL 5019 capriblau"]
    - [3, 033_Ti3_Geschicklichkeit_Manga.mp3, "RAL 3022 lachsrot"]
    - [3, 033e_Ti3_skill_Manga.mp3, "RAL 3013 tomatenrot"]
    - [3, 034_Ti3_Geschicklichkeit_Nbg-Docke.mp3, "RAL 5018 türkisblau"]
    - [3, 034e_Ti3_skill_Nbg-Docke.mp3, "RAL 6034 pasteltürkis"]
    - [3, 035_Ti3_Geschicklichkeit_Roboter.mp3, "RAL 1000 grünbeige"]
    - [3, 035e_Ti3_skill_Roboter.mp3, "RAL 6021 blassgrün"]
    - [4, 041_Ti4_Beziehung_Albrecht-Duerer.mp3, "RAL 1003 gelb"]
    - [4, 041e_Ti4_relationship_Albrecht-Duerer.mp3, "RAL 1001 beige"]
    - [4, 042_Ti4_Beziehung_Lara-Croft.mp3, "RAL 5024 pastelblau"]
    - [4, 042e_Ti4_relationship_Lara-Croft.mp3, "RAL 5019 capriblau"]
    - [4, 043_Ti4_Beziehung_Manga.mp3, "RAL 3022 lachsrot"]
    - [4, 043e_Ti4_relationship_Manga.mp3, "RAL 3013 tomatenrot"]
    - [4, 044_Ti4_Beziehung_Nbg-Docke.mp3, "RAL 5018 türkisblau"]
    - [4, 044e_Ti4_relationship_Nbg-Docke.mp3, "RAL 6034 pasteltürkis"]
    - [4, 045_Ti4_Beziehung_Roboter.mp3, "RAL 1000 grünbeige"]
    - [4, 045e_Ti4_relationship_Roboter.mp3, "RAL 6021 blassgrün"]
    - [5, 051_Ti5_Begreifen_Albrecht-Duerer.mp3, "RAL 1003 gelb"]
    - [5, 051e_Ti5_toknow_Albrecht-Duerer.mp3, "RAL 1001 beige"]
    - [5, 052_Ti5_Begreifen_Lara-Croft.mp3, "RAL 5024 pastelblau"]
    - [5, 052e_Ti5_toknow_Lara-Croft.mp3, "RAL 5019 capriblau"]
    - [5, 053_Ti5_Begreifen_Manga.mp3, "RAL 3022 lachsrot"]
    - [5, 053e_Ti5_toknow_Manga.mp3, "RAL 3013 tomatenrot"]
    - [5, 054_Ti5_Begreifen_Nbg-Docke.mp3, "RAL 5018 türkisblau"]
    - [5, 054e_Ti5_toknow_Nbg-Docke.mp3, "RAL 6034 pasteltürkis"]
    - [5, 055_Ti5_Begreifen_Roboter.mp3, "RAL 1000 grünbeige"]
    - [5, 055e_Ti5_toknow_Roboter.mp3, "RAL 6021 blassgrün"]
    - [6, 061_Ti6_Strategie_Albrecht-Duerer.mp3, "RAL 1003 gelb"]
    - [6, 061e_Ti6_strategy_Albrecht-Duerer.mp3, "RAL 1001 beige"]
    - [6, 062_Ti6_Strategie_Lara-Croft.mp3, "RAL 5024 pastelblau"]
    - [6, 062e_Ti6_strategy_Lara-Croft.mp3, "RAL 5019 capriblau"]
    - [6, 063_Ti6_Strategie_Manga.mp3, "RAL 3022 lachsrot"]
    - [6, 063e_Ti6_strategy_Manga.mp3, "RAL 3013 tomatenrot"]
    - [6, 064_Ti6_Strategie_Nbg-Docke.mp3, "RAL 5018 türkisblau"]
    - [6, 064e_Ti6_strategy_Nbg-Docke.mp3, "RAL 6034 pasteltürkis"]
    - [6, 065_Ti6_Strategie_Roboter.mp3, "RAL 1000 grünbeige"]
    - [6, 065e_Ti6_strategy_Roboter.mp3, "RAL 6021 blassgrün"]
    - [7, 071_Ti7_Technik_Albrecht-Duerer.mp3, "RAL 1003 gelb"]
    - [7, 071e_Ti7_technics_Albrecht-Duerer.mp3, "RAL 1001 beige"]
    - [7, 072_Ti7_Technik_Lara-Croft.mp3, "RAL 5024 pastelblau"]
    - [7, 072e_Ti7_technics_Lara-Croft.mp3, "RAL 5019 capriblau"]
    - [7, 073_Ti7_Technik_Manga.mp3, "RAL 3022 lachsrot"]
    - [7, 073e_Ti7_technics_Manga.mp3, "RAL 3013 tomatenrot"]
    - [7, 074_Ti7_Technik_Nbg-Docke.mp3, "RAL 5018 türkisblau"]
    - [7, 074e_Ti7_technics_Nbg-Docke.mp3, "RAL 6034 pasteltürkis"]
    - [7, 075_Ti7_Technik_Roboter.mp3, "RAL 1000 grünbeige"]
    - [7, 075e_Ti7_technics_Roboter.mp3, "RAL 6021 blassgrün"]
    - [8, 081_Ti8_Wirtschaften_Albrecht-Duerer.mp3, "RAL 1003 gelb"]
    - [8, 081e_Ti8_economics_Albrecht-Duerer.mp3, "RAL 1001 beige"]
    - [8, 082_Ti8_Wirtschaften_Lara-Croft.mp3, "RAL 5024 pastelblau"]
    - [8, 082e_Ti8_economics_Lara-Croft.mp3, "RAL 5019 capriblau"]
    - [8, 083_Ti8_Wirtschaften_Manga.mp3, "RAL 3022 lachsrot"]
    - [8, 083e_Ti8_economics_Manga.mp3, "RAL 3013 tomatenrot"]
    - [8, 084_Ti8_Wirtschaften_Nbg-Docke.mp3, "RAL 5018 türkisblau"]
    - [8, 084e_Ti8_economics_Nbg-Docke.mp3, "RAL 6034 pasteltürkis"]
    - [8, 085_Ti8_Wirtschaften_Roboter.mp3, "RAL 1000 grünbeige"]
    - [8, 085e_Ti8_economics_Roboter.mp3, "RAL 6021 blassgrün"]

