color:
-   - "RAL 1000 - Gr\xFCnbeige"
    - [4080, 3300, 2328]
-   - RAL 1001 - Beige
    - [4188, 3079, 2263]
-   - RAL 1002 - Sandgelb
    - [3888, 2799, 1889]
-   - RAL 1003 - Signalgelb
    - [4812, 2828, 1466]
-   - RAL 1004 - Goldgelb
    - [4172, 2535, 1356]
-   - RAL 1005 - Honiggelb
    - [3232, 2102, 1196]
-   - RAL 1006 - Maisgelb
    - [4016, 2272, 1310]
-   - RAL 1007 - Narzissengelb
    - [4048, 2140, 1228]
-   - RAL 1011 - Braunbeige
    - [2764, 1849, 1347]
-   - RAL 1012 - Zitronengelb
    - [3851, 2708, 1530]
-   - "RAL 1013 - Perlwei\xDF"
    - [5165, 4411, 3649]
-   - RAL 1014 - Elfenbein
    - [4541, 3593, 2631]
-   - RAL 1015 - Hellelfenbein
    - [5117, 4189, 3297]
-   - RAL 1016 - Schwefelgelb
    - [5651, 4455, 2353]
-   - RAL 1017 - Safrangelb
    - [4890, 2856, 1728]
-   - RAL 5008 - Graublau
    - [1026, 914, 842]
-   - RAL 5009 - Azurblau
    - [1116, 1216, 1280]
-   - RAL 5010 - Enzianblau
    - [973, 1073, 1316]
-   - RAL 5011 - Stahlblau
    - [887, 783, 752]
-   - RAL 5012 - Lichtblau
    - [1476, 1990, 2394]
-   - RAL 5013 - Kobaltblau
    - [926, 839, 878]
-   - RAL 5014 - Taubenblau
    - [1761, 1764, 1822]
-   - RAL 5015 - Himmelblau
    - [1249, 1745, 2243]
-   - RAL 5017 - Verkehrsblau
    - [984, 1202, 1554]
-   - "RAL 5018 - T\xFCrkisblau"
    - [1451, 1959, 1856]
-   - RAL 5019 - Capriblau
    - [1022, 1207, 1422]
-   - RAL 5020 - Ozeanblau
    - [894, 888, 873]
-   - RAL 5021 - Wasserblau
    - [1114, 1494, 1449]
-   - RAL 5022 - Nachtblau
    - [952, 851, 912]
-   - RAL 5023 - Fernblau
    - [1351, 1440, 1592]
desc: DEFAULT DESCRIPTION
det: {threshold: 2}
map_station_mp3_color:
- [1, 011_Ti1_Rollenspiel_Albrecht-Duerer.mp3, RAL 1003 gelb]
- [1, 011e_Ti1_Roleplay_Albrecht-Duerer.mp3, RAL 1001 beige]
- [1, 012_Ti1_Rollenspiel_Lara-Croft.mp3, RAL 5024 pastelblau]
- [1, 012e_Ti1_Roleplay_Lara-Croft.mp3, RAL 5019 capriblau]
- [1, 013_Ti1_Rollenspiel_Manga.mp3, RAL 3022 lachsrot]
- [1, 013e_Ti1_Roleplay_Manga.mp3, RAL 3013 tomatenrot]
- [1, 014_Ti1_Rollenspiel_Nbg-Docke.mp3, "RAL 5018 t\xFCrkisblau"]
- [1, 014e_Ti1_Roleplay_Nbg-Docke.mp3, "RAL 6034 pastelt\xFCrkis"]
- [1, 015_Ti1_Rollenspiel_Roboter.mp3, "RAL 1000 gr\xFCnbeige"]
- [1, 015e_Ti1_Roleplay_Roboter.mp3, "RAL 6021 blassgr\xFCn"]
- [2, 021_Ti2_bauen-konstruieren_Albrecht-Duerer.mp3, RAL 1003 gelb]
- [2, 021e_Ti2_construction_Albrecht-Duerer.mp3, RAL 1001 beige]
- [2, 022_Ti2_bauen-konstruieren_Lara-Croft.mp3, RAL 5024 pastelblau]
- [2, 022e_Ti2_construction_Lara-Croft.mp3, RAL 5019 capriblau]
- [2, 023_Ti2_bauen-konstruieren_Manga.mp3, RAL 3022 lachsrot]
- [2, 023e_Ti2_construction_Manga.mp3, RAL 3013 tomatenrot]
- [2, 024_Ti2_bauen-konstruieren_Nbg-Docke.mp3, "RAL 5018 t\xFCrkisblau"]
- [2, 024e_Ti2_construction_Nbg-Docke.mp3, "RAL 6034 pastelt\xFCrkis"]
- [2, 025_Ti2_bauen-konstruieren_Roboter.mp3, "RAL 1000 gr\xFCnbeige"]
- [2, 025e_Ti2_construction_Roboter.mp3, "RAL 6021 blassgr\xFCn"]
- [3, 031_Ti3_Geschicklichkeit_Albrecht-Duerer.mp3, RAL 1003 gelb]
- [3, 031e_Ti3_skill_Albrecht-Duerer.mp3, RAL 1001 beige]
- [3, 032_Ti3_Geschicklichkeit_Lara-Croft.mp3, RAL 5024 pastelblau]
- [3, 032e_Ti3_skill_Lara-Croft.mp3, RAL 5019 capriblau]
- [3, 033_Ti3_Geschicklichkeit_Manga.mp3, RAL 3022 lachsrot]
- [3, 033e_Ti3_skill_Manga.mp3, RAL 3013 tomatenrot]
- [3, 034_Ti3_Geschicklichkeit_Nbg-Docke.mp3, "RAL 5018 t\xFCrkisblau"]
- [3, 034e_Ti3_skill_Nbg-Docke.mp3, "RAL 6034 pastelt\xFCrkis"]
- [3, 035_Ti3_Geschicklichkeit_Roboter.mp3, "RAL 1000 gr\xFCnbeige"]
- [3, 035e_Ti3_skill_Roboter.mp3, "RAL 6021 blassgr\xFCn"]
- [4, 041_Ti4_Beziehung_Albrecht-Duerer.mp3, RAL 1003 gelb]
- [4, 041e_Ti4_relationship_Albrecht-Duerer.mp3, RAL 1001 beige]
- [4, 042_Ti4_Beziehung_Lara-Croft.mp3, RAL 5024 pastelblau]
- [4, 042e_Ti4_relationship_Lara-Croft.mp3, RAL 5019 capriblau]
- [4, 043_Ti4_Beziehung_Manga.mp3, RAL 3022 lachsrot]
- [4, 043e_Ti4_relationship_Manga.mp3, RAL 3013 tomatenrot]
- [4, 044_Ti4_Beziehung_Nbg-Docke.mp3, "RAL 5018 t\xFCrkisblau"]
- [4, 044e_Ti4_relationship_Nbg-Docke.mp3, "RAL 6034 pastelt\xFCrkis"]
- [4, 045_Ti4_Beziehung_Roboter.mp3, "RAL 1000 gr\xFCnbeige"]
- [4, 045e_Ti4_relationship_Roboter.mp3, "RAL 6021 blassgr\xFCn"]
- [5, 051_Ti5_Begreifen_Albrecht-Duerer.mp3, RAL 1003 gelb]
- [5, 051e_Ti5_toknow_Albrecht-Duerer.mp3, RAL 1001 beige]
- [5, 052_Ti5_Begreifen_Lara-Croft.mp3, RAL 5024 pastelblau]
- [5, 052e_Ti5_toknow_Lara-Croft.mp3, RAL 5019 capriblau]
- [5, 053_Ti5_Begreifen_Manga.mp3, RAL 3022 lachsrot]
- [5, 053e_Ti5_toknow_Manga.mp3, RAL 3013 tomatenrot]
- [5, 054_Ti5_Begreifen_Nbg-Docke.mp3, "RAL 5018 t\xFCrkisblau"]
- [5, 054e_Ti5_toknow_Nbg-Docke.mp3, "RAL 6034 pastelt\xFCrkis"]
- [5, 055_Ti5_Begreifen_Roboter.mp3, "RAL 1000 gr\xFCnbeige"]
- [5, 055e_Ti5_toknow_Roboter.mp3, "RAL 6021 blassgr\xFCn"]
- [6, 061_Ti6_Strategie_Albrecht-Duerer.mp3, RAL 1003 gelb]
- [6, 061e_Ti6_strategy_Albrecht-Duerer.mp3, RAL 1001 beige]
- [6, 062_Ti6_Strategie_Lara-Croft.mp3, RAL 5024 pastelblau]
- [6, 062e_Ti6_strategy_Lara-Croft.mp3, RAL 5019 capriblau]
- [6, 063_Ti6_Strategie_Manga.mp3, RAL 3022 lachsrot]
- [6, 063e_Ti6_strategy_Manga.mp3, RAL 3013 tomatenrot]
- [6, 064_Ti6_Strategie_Nbg-Docke.mp3, "RAL 5018 t\xFCrkisblau"]
- [6, 064e_Ti6_strategy_Nbg-Docke.mp3, "RAL 6034 pastelt\xFCrkis"]
- [6, 065_Ti6_Strategie_Roboter.mp3, "RAL 1000 gr\xFCnbeige"]
- [6, 065e_Ti6_strategy_Roboter.mp3, "RAL 6021 blassgr\xFCn"]
- [7, 071_Ti7_Technik_Albrecht-Duerer.mp3, RAL 1003 gelb]
- [7, 071e_Ti7_technics_Albrecht-Duerer.mp3, RAL 1001 beige]
- [7, 072_Ti7_Technik_Lara-Croft.mp3, RAL 5024 pastelblau]
- [7, 072e_Ti7_technics_Lara-Croft.mp3, RAL 5019 capriblau]
- [7, 073_Ti7_Technik_Manga.mp3, RAL 3022 lachsrot]
- [7, 073e_Ti7_technics_Manga.mp3, RAL 3013 tomatenrot]
- [7, 074_Ti7_Technik_Nbg-Docke.mp3, "RAL 5018 t\xFCrkisblau"]
- [7, 074e_Ti7_technics_Nbg-Docke.mp3, "RAL 6034 pastelt\xFCrkis"]
- [7, 075_Ti7_Technik_Roboter.mp3, "RAL 1000 gr\xFCnbeige"]
- [7, 075e_Ti7_technics_Roboter.mp3, "RAL 6021 blassgr\xFCn"]
- [8, 081_Ti8_Wirtschaften_Albrecht-Duerer.mp3, RAL 1003 gelb]
- [8, 081e_Ti8_economics_Albrecht-Duerer.mp3, RAL 1001 beige]
- [8, 082_Ti8_Wirtschaften_Lara-Croft.mp3, RAL 5024 pastelblau]
- [8, 082e_Ti8_economics_Lara-Croft.mp3, RAL 5019 capriblau]
- [8, 083_Ti8_Wirtschaften_Manga.mp3, RAL 3022 lachsrot]
- [8, 083e_Ti8_economics_Manga.mp3, RAL 3013 tomatenrot]
- [8, 084_Ti8_Wirtschaften_Nbg-Docke.mp3, "RAL 5018 t\xFCrkisblau"]
- [8, 084e_Ti8_economics_Nbg-Docke.mp3, "RAL 6034 pastelt\xFCrkis"]
- [8, 085_Ti8_Wirtschaften_Roboter.mp3, "RAL 1000 gr\xFCnbeige"]
- [8, 085e_Ti8_economics_Roboter.mp3, "RAL 6021 blassgr\xFCn"]
rgb: {max_dist: 200, stable_cnt: 5, stable_dist: 10}
sensor:
    gain: !!python/tuple [2]
    integration_time: !!python/tuple [235]
