color:
-   - "Würfel blau"
    - [3049.0, 3580.0, 3656.0]
-   - "Würfel gelb"
    - [5877.0, 4771.0, 3147.0]
-   - "Würfel orange"
    - [5129.0, 3434.0, 2719.0]
-   - "Würfel weiss"
    - [6037.0, 5466.0, 4849.0]
-   - "Würfel rot"
    - [4623.0, 2855.0, 2770.0]
desc: "Configuration file für ersten Testaufbau mit Würfelhalter und schwarzen Schirmwürfel mittel"
det: {threshold: 2}
# max_dist: max distance between rgb colors.
rgb: {stable_cnt: 10, stable_dist: 7, max_dist: 2000}
sensor:
    gain: !!python/tuple [2]
    integration_time: !!python/tuple [235]
